### ISSUE TITLE
Malformed characters can cause Data::Printer to loop using 100% CPU

### ISSUE THREAD

**Issue by nigelm** [garu/Data-Printer#114] opened 2017-07-07 20:15 UTC
Apologies for the really poor bug report, but it appears to be possible to cause Data::Printer to go into an infinite loop by passing it some broken unicode strings.

Code basically grabbed some XML data using a REST call (LWP to fetch), used xml2hash from XML::Fast to make a hash structure and then dumped the hash using p($hash).  Half the hash printed and then the system sat using 100% CPU for as long as I left it.

The Unicode issue appears to be a mismatch within XML::Fast (problem was avoided by forcing that to do some decode there).  Other code was complaining about:-

    Malformed UTF-8 character: \xa3 (unexpected continuation byte 0xa3, with no preceding start byte)

Although the underlying problems forcing this problem are fixed I think I have a set of data files around that *ought* to be able to reproduce this.

Version of `Data::Printer` is 0.39 running on perlbrew built perl 5.26.0 on a Mac.

**Comment by dur-randir** [comment] 2017-07-09 23:24
Hi, can you please provide a more detailed test case? Just feeding utf8 malformation on 5.26 caused no problems for me.

**Comment by garu** [comment] 2018-03-19 12:38
Hi @nigelm! As @dur-randir said, we need a little more information to fix this. Were you able to reproduce it again at all? Anything else that might help us would be greatly appreciated.

If the code to reproduce it is sensible in some way and you don't want to put it on github, feel free to send it to my email privately and I'll delete everything as soon as I can reproduce/fix the issue. Otherwise we can also help debug it blindly, but we need _some_ feedback :)

**Comment by garu** [comment] 2018-05-14 02:11
I'm going to close this issue because we're unable to reproduce it. But if you manage to do so don't hesitate to reopen!

Thanks again for taking the time to file this!

**Closed by garu** 2018-05-14 02:11 UTC
