### ISSUE TITLE
0.40: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [garu/Data-Printer#146] opened 2020-05-10 12:22 UTC
```
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
# Beginning Data::Printer tests in linux with Perl 5.030001, /usr/bin/perl
# Testing Data::Printer 0.40
t/00-load.t ................. ok
t/00.2-begin_load.t ......... ok
t/01-p.t .................... ok
t/02-colors.t ............... ok
t/02.2-autocolor.t .......... ok
t/03-conf.t ................. ok
t/03-conf_not_ref.t ......... ok
t/04-multiline.t ............ ok
t/04-multiline2.t ........... ok
t/05-obj.t .................. ok
t/06-obj2.t ................. ok
t/07-sort.t ................. ok
t/08-deparse.t .............. ok
t/09-alias.t ................ ok
t/10-filter.t ............... ok
t/11-aliased_with_filter.t .. ok
t/12-filter_class.t ......... ok
t/13-filter_datetime.t ...... ok
DBIx::Class::Storage::DBI::_warn_undetermined_driver(): This version of DBIC does not yet seem to supply a driver for your particular RDBMS and/or connection method ('DBM'). While we will attempt to continue anyway, the results are likely to be underwhelming. Please upgrade DBIC, and if this message does not go away, file a bugreport including the following info:
{
  DBD => "DBD::DBM",
  DBD_VER => "0.08",
  DBIC_DRIVER => "DBIx::Class::Storage::DBI",
  DBIC_DSN => "dbi:DBM(RaiseError=1):",
  DBIC_VER => "0.082841",
  DBI_VER => "1.643",
}
t/13.2-filter_db.t .......... ok
t/13.3-filter_digest.t ...... ok
t/14-local_conf.t ........... ok
t/15-rc_file.t .............. ok
t/16-rc_file2.t ............. ok
t/16.2-rc_overwrite.t ....... ok
t/16.3-rc_env.t ............. ok
t/16.4-rc_env2.t ............ ok
t/16.5-rc_env3.t ............ ok
t/17-parallel.t ............. ok
t/18-class_method.t ......... ok
t/19-tied.t ................. ok
t/20-handles.t .............. ok
t/21-ddp.t .................. ok
t/22-class_method.t ......... ok
t/23-caller_info.t .......... ok
t/24-no_prototypes.t ........ ok
t/25-weak.t ................. ok
t/26-tainted.t .............. ok
*** WARNING *** taint mode on: skipping rc file '/tmp/Pbg43NC3ui/my_home/.dataprinter'.
t/26.2-tainted_rc.t ......... ok
t/26.7-unicode.t ............ ok
t/27-pass_through.t ......... ok
t/27.2-pass_through.t ....... ok
t/27.3-pass_through-DDP.t ... ok
t/27.4-pass_through-DDP.t ... ok
t/28-void_return.t .......... ok
t/29-output.t ............... ok
t/30-print_escapes.t ........ ok
t/31-bad_parameters.t ....... ok
t/32-quote_keys.t ........... ok
t/33-end_separator.t ........ ok
t/33-separator.t ............ ok
t/34-show_readonly.t ........ ok
t/35-vstrings.t ............. ok
t/36-valign.t ............... ok
t/37-format.t ............... ok
t/38-lvalue.t ............... ok
t/39-seen_override.t ........ ok
t/40-escape_chars.t ......... ok

#   Failed test 'testing odd objects (YAML::Syck)'
#   at t/41-yaml.t line 30.
#          got: '\ {
#     sample   [
#         [0] {
#             name    "foo",
#             value   "bar"
#         }
#     ]
# }'
#     expected: '\ {
#     sample   [
#         [0] some.method  {
#             public methods (0)
#             private methods (0)
#             internals: {
#                 name    "foo",
#                 value   "bar"
#             }
#         }
#     ]
# }'
# Looks like you failed 1 test of 1.
t/41-yaml.t .................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
t/42-alignment.t ............ ok
t/43-_is_number.t ........... ok
t/44-number-colors.t ........ ok
t/45-np.t ................... ok

Test Summary Report
-------------------
t/41-yaml.t               (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=62, Tests=458,  7 wallclock secs ( 0.35 usr  0.34 sys +  5.12 cusr  1.73 csys =  7.54 CPU)
Result: FAIL
Failed 1/62 test programs. 1/458 subtests failed.
make: *** [Makefile:877: test_dynamic] Error 255
```

**Comment by eserte** [comment] 2020-09-09 10:08
Duplicate of https://github.com/garu/Data-Printer/issues/142

**Comment by garu** [comment] 2021-02-24 13:49
Hello! I am pleased to announce Data::Printer 1.0.0 is released, and right now all tests pass <3

Please file a new issue if anything comes up.

Thank you again for using Data::Printer and for taking the time to file this report.

**Closed by garu** 2021-02-24 13:49 UTC
